#!/usr/bin/env zsh
#
set -euo pipefail

dotfiles="$(realpath $(dirname $0))"
sourcepath="$dotfiles/.zshrc"

export DOTFILES=$dotfiles

cd $dotfiles

# Install hpmebrew if it doesn't exist already
if ! type brew > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install necessities
brew install --quiet \
  kitty \
  tmux \
  neovim \
  ranger \
  bat \
  tldr \
  zoxide \
  fzf \
  ripgrep \
  node \
  black \
  git-branchless \
  jj

./setup/install-fonts.sh

echo "Configuring jj"
./setup/jj.sh

if [ ! -f ~/.tmux.conf ]; then
  echo "Link ~/.tmux.conf -> dotfiles/tmux.conf"
  ln -s $dotfiles/tmux.conf ~/.tmux.conf
fi

# TODO: Recognize directory vs a symlink

if [ ! -d ~/.config/nvim ]; then
  echo "link ~/.config/nvim -> dotfiles/.config/nvim"
  ln -s $dotfiles/.config/nvim ~/.config/nvim
fi

if [ ! -d ~/.config/kitty ]; then
  echo "link ~/.config/kitty -> dotfiles/.config/kitty"
  ln -s $dotfiles/.config/kitty ~/.config/kitty
fi

if ! grep -q $sourcepath ~/.zshrc; then
  echo "export DOTFILES=$dotfiles"
  echo "export DOTFILES=$dotfiles" >> ~/.zshrc

  echo "source .zshrc in ~/.zshrc"
  echo "source $sourcepath" >> ~/.zshrc
fi

