#!/usr/bin/env zsh
#
set -euo pipefail

dotfiles="$(realpath $(dirname $0))"
cd $dotfiles

# Install hpmebrew if it doesn't exist already
if ! type brew > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! type home-manager > /dev/null; then
  echo "Installing home-manager"
  sh <(curl -L https://nixos.org/nix/install)
  nix-channel --add https://nixos.org/channels/nixpkgs-unstable unstable
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi

# Install necessities
brew uninstall --quiet \
  kitty \
  tmux \
  neovim \
  ranger \
  bat \
  tldr \
  zoxide \
  fzf \
  ripgrep \
  node \
  black \
  git-branchless \
  jj || true

echo "Configuring jj"
./setup/jj.sh

