#!/usr/bin/env bash

set -euo pipefail

# The main commit might have leftover branches.
mains="$(git branchless query -b 'main()')"
main=""
for branch in $mains; do
    if [[ "$branch" =~ ^(main|master|develop|dev)$ ]]; then
        main="$branch"
        break
    fi
done

if [[ -z "$main" ]]; then
    echo "No main branch found"
    exit 1
fi

git branchless sync --pull

branch_previous="$main"
for branch in $(git branchless query -b 'stack()'); do
    git push origin $branch --force-with-lease \
        -o merge_request.create \
        -o merge_request.target=$branch_previous \
        -o merge_request.remove_source_branch
    branch_previous="$branch"
done
