#!/usr/bin/env bash

set -euo pipefail

git branchless sync --pull

main="$(git branchless query -b 'main()')"

branch_previous="$main"
for branch in $(git branchless query -b 'stack()'); do
    git push origin $branch --force-with-lease \
        -o merge_request.create -o merge_request.target=$branch_previous
    branch_previous="$branch"
done
